using System;
using System.Text;

namespace libVT100
{
    /// <summary>
    /// Delegate for handling output generated by a terminal decoder back to the host system (e.g. CPR, DA queries).
    /// </summary>
    /// <param name="_decoder">The decoder generating the output.</param>
    /// <param name="_output">Raw byte array to be transmitted to the host.</param>
    public delegate void DecoderOutputDelegate(IDecoder _decoder, byte[] _output);

    /// <summary>
    /// Core interface for terminal stream decoders capable of consuming input bytes and generating terminal responses.
    /// </summary>
    public interface IDecoder : IDisposable    
    {
        /// <summary>
        /// Gets or sets the text encoding used by the stream decoder (e.g. UTF-8 or ASCII).
        /// </summary>
        Encoding Encoding { get; set; }

        /// <summary>
        /// Feeds raw input byte data into the decoder stream.
        /// If an invalid sequence is encountered, the decoder recovers gracefully and resumes decoding.
        /// </summary>
        /// <param name="_data">Raw byte payload received from the terminal transport stream.</param>
        void Input(byte[] _data);
        
        /// <summary>
        /// Event triggered when the terminal emulator emits an escape sequence response back to the host.
        /// </summary>
        event DecoderOutputDelegate? Output;

        /// <summary>
        /// Notifies the decoder that a special key or modifier key combination was pressed.
        /// </summary>
        /// <param name="_modifiers">Active keyboard modifiers (Shift, Control, Alt).</param>
        /// <param name="_key">Virtual key code.</param>
        /// <returns>True if the key was recognized and processed; otherwise, false.</returns>
        bool KeyPressed(Keys _modifiers, Keys _key);

        /// <summary>
        /// Notifies the decoder that a standard character was typed on the keyboard.
        /// </summary>
        /// <param name="_character">Character typed.</param>
        void CharacterTyped(char _character);
    }
}

